-- Seed 150 DSA Problems into the database
-- Fix the UUID column type so we can insert string IDs like dsa-001
ALTER TABLE problems ALTER COLUMN id TYPE text USING id::text;
ALTER TABLE user_progress ALTER COLUMN problem_id TYPE text USING problem_id::text;

-- Ensure columns exist
ALTER TABLE problems ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE problems ADD COLUMN IF NOT EXISTS leetcode_url TEXT;

INSERT INTO problems (id, category, title, slug, difficulty, description, leetcode_url) VALUES
('dsa-001', 'Arrays & Hashing', 'Contains Duplicate', '', 'Easy', 'Given an integer array nums, return true if any value appears at least twice in the array, and return false if every element is distinct.', 'https://leetcode.com/problems/contains-duplicate/'),
('dsa-002', 'Arrays & Hashing', 'Valid Anagram', '', 'Easy', 'Given two strings s and t, return true if t is an anagram of s, and false otherwise.', 'https://leetcode.com/problems/valid-anagram/'),
('dsa-003', 'Arrays & Hashing', 'Two Sum', '', 'Easy', 'Given an array of integers nums and an integer target, return indices of the two numbers such that they add up to target.', 'https://leetcode.com/problems/two-sum/'),
('dsa-004', 'Arrays & Hashing', 'Group Anagrams', '', 'Medium', 'Given an array of strings strs, group the anagrams together. You can return the answer in any order.', 'https://leetcode.com/problems/group-anagrams/'),
('dsa-005', 'Arrays & Hashing', 'Top K Frequent Elements', '', 'Medium', 'Given an integer array nums and an integer k, return the k most frequent elements. You may return the answer in any order.', 'https://leetcode.com/problems/top-k-frequent-elements/'),
('dsa-006', 'Two Pointers', 'Valid Palindrome', '', 'Easy', 'A phrase is a palindrome if, after converting all uppercase letters into lowercase letters and removing all non-alphanumeric characters, it reads the same forward and backward.', 'https://leetcode.com/problems/valid-palindrome/'),
('dsa-007', 'Two Pointers', '3Sum', '', 'Medium', 'Given an integer array nums, return all the triplets [nums[i], nums[j], nums[k]] such that i != j, i != k, and j != k, and nums[i] + nums[j] + nums[k] == 0.', 'https://leetcode.com/problems/3sum/'),
('dsa-008', 'Two Pointers', 'Container With Most Water', '', 'Medium', 'You are given an integer array height of length n. There are n vertical lines drawn such that the two endpoints of the ith line are (i, 0) and (i, height[i]). Find two lines that together with the x-axis form a container, such that the container contains the most water.', 'https://leetcode.com/problems/container-with-most-water/'),
('dsa-009', 'Stack', 'Valid Parentheses', '', 'Easy', 'Given a string s containing just the characters ''('', '')'', ''{'', ''}'', ''['' and '']'', determine if the input string is valid.', 'https://leetcode.com/problems/valid-parentheses/'),
('dsa-010', 'Stack', 'Min Stack', '', 'Medium', 'Design a stack that supports push, pop, top, and retrieving the minimum element in constant time.', 'https://leetcode.com/problems/min-stack/'),
('dsa-011', 'Sliding Window', 'Best Time to Buy and Sell Stock', '', 'Easy', 'You are given an array prices where prices[i] is the price of a given stock on the ith day. You want to maximize your profit by choosing a single day to buy one stock and choosing a different day in the future to sell that stock.', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock/'),
('dsa-012', 'Sliding Window', 'Longest Substring Without Repeating Characters', '', 'Medium', 'Given a string s, find the length of the longest substring without repeating characters.', 'https://leetcode.com/problems/longest-substring-without-repeating-characters/'),
('dsa-013', 'Linked List', 'Reverse Linked List', '', 'Easy', 'Given the head of a singly linked list, reverse the list, and return the reversed list.', 'https://leetcode.com/problems/reverse-linked-list/'),
('dsa-014', 'Linked List', 'Merge Two Sorted Lists', '', 'Easy', 'Merge the two lists in a one sorted list. The list should be made by splicing together the nodes of the first two lists.', 'https://leetcode.com/problems/merge-two-sorted-lists/'),
('dsa-015', 'Linked List', 'Reorder List', '', 'Medium', 'You are given the head of a singly linked-list. The list can be represented as: L0 → L1 → … → Ln - 1 → Ln. Reorder the list to be on the following form: L0 → Ln → L1 → Ln - 1 → L2 → Ln - 2 → …', 'https://leetcode.com/problems/reorder-list/'),
('dsa-016', 'Trees', 'Invert Binary Tree', '', 'Easy', 'Given the root of a binary tree, invert the tree, and return its root.', 'https://leetcode.com/problems/invert-binary-tree/'),
('dsa-017', 'Trees', 'Maximum Depth of Binary Tree', '', 'Easy', 'Given the root of a binary tree, return its maximum depth.', 'https://leetcode.com/problems/maximum-depth-of-binary-tree/'),
('dsa-018', 'Trees', 'Diameter of Binary Tree', '', 'Easy', 'Given the root of a binary tree, return the length of the diameter of the tree.', 'https://leetcode.com/problems/diameter-of-binary-tree/'),
('dsa-019', 'Trees', 'Lowest Common Ancestor of a Binary Search Tree', '', 'Medium', 'Given a binary search tree (BST), find the lowest common ancestor (LCA) node of two given nodes in the BST.', 'https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/'),
('dsa-020', 'Trees', 'Binary Tree Level Order Traversal', '', 'Medium', 'Given the root of a binary tree, return the level order traversal of its nodes'' values. (i.e., from left to right, level by level).', 'https://leetcode.com/problems/binary-tree-level-order-traversal/'),
('dsa-021', 'Tries', 'Implement Trie (Prefix Tree)', '', 'Medium', 'A trie (pronounced as ''try'') or prefix tree is a tree data structure used to efficiently store and retrieve keys in a dataset of strings. Implement the Trie class.', 'https://leetcode.com/problems/implement-trie-prefix-tree/'),
('dsa-022', 'Tries', 'Design Add and Search Words Data Structure', '', 'Medium', 'Design a data structure that supports adding new words and finding if a string matches any previously added string. The search string can contain ''.'' to match any letter.', 'https://leetcode.com/problems/design-add-and-search-words-data-structure/'),
('dsa-023', 'Heap / Priority Queue', 'Kth Largest Element in a Stream', '', 'Easy', 'Design a class to find the kth largest element in a stream.', 'https://leetcode.com/problems/kth-largest-element-in-a-stream/'),
('dsa-024', 'Heap / Priority Queue', 'Last Stone Weight', '', 'Easy', 'You are given an array of integers stones where stones[i] is the weight of the ith stone. Smash the two heaviest stones together until there is at most one stone left.', 'https://leetcode.com/problems/last-stone-weight/'),
('dsa-025', 'Heap / Priority Queue', 'K Closest Points to Origin', '', 'Medium', 'Given an array of points where points[i] = [xi, yi] represents a point on the X-Y plane and an integer k, return the k closest points to the origin (0, 0).', 'https://leetcode.com/problems/k-closest-points-to-origin/'),
('dsa-026', 'Backtracking', 'Subsets', '', 'Medium', 'Given an integer array nums of unique elements, return all possible subsets (the power set). The solution set must not contain duplicate subsets.', 'https://leetcode.com/problems/subsets/'),
('dsa-027', 'Backtracking', 'Combination Sum', '', 'Medium', 'Given an array of distinct integers candidates and a target integer target, return a list of all unique combinations of candidates where the chosen numbers sum to target.', 'https://leetcode.com/problems/combination-sum/'),
('dsa-028', 'Graphs', 'Number of Islands', '', 'Medium', 'Given an m x n 2D binary grid grid which represents a map of ''1''s (land) and ''0''s (water), return the number of islands.', 'https://leetcode.com/problems/number-of-islands/'),
('dsa-029', 'Graphs', 'Clone Graph', '', 'Medium', 'Return a deep copy (clone) of a graph. Each node in the graph contains a value (int) and a list (List[Node]) of its neighbors.', 'https://leetcode.com/problems/clone-graph/'),
('dsa-030', 'Graphs', 'Course Schedule', '', 'Medium', 'There are a total of numCourses courses you have to take, labeled from 0 to numCourses - 1. You are given an array prerequisites where prerequisites[i] = [ai, bi] indicates that you must take course bi first if you want to take course ai. Return true if you can finish all courses.', 'https://leetcode.com/problems/course-schedule/'),
('dsa-031', 'Advanced Graphs', 'Network Delay Time', '', 'Medium', 'You are given a network of n nodes, labeled from 1 to n. You are given times, a list of travel times as directed edges times[i] = (ui, vi, wi), where ui is the source node, vi is the target node, and wi is the time it takes for a signal to travel from source to target. Return the minimum time it takes for all the n nodes to receive the signal.', 'https://leetcode.com/problems/network-delay-time/'),
('dsa-032', '1D Dynamic Programming', 'Climbing Stairs', '', 'Easy', 'You are climbing a staircase. It takes n steps to reach the top. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?', 'https://leetcode.com/problems/climbing-stairs/'),
('dsa-033', '1D Dynamic Programming', 'Min Cost Climbing Stairs', '', 'Easy', 'You are given an integer array cost where cost[i] is the cost of ith step on a staircase. Once you pay the cost, you can either climb one or two steps. You can either start from the step with index 0, or the step with index 1. Return the minimum cost to reach the top of the floor.', 'https://leetcode.com/problems/min-cost-climbing-stairs/'),
('dsa-034', '1D Dynamic Programming', 'House Robber', '', 'Medium', 'You are a professional robber planning to rob houses along a street. Each house has a certain amount of money stashed, the only constraint stopping you from robbing each of them is that adjacent houses have security systems connected and it will automatically contact the police if two adjacent houses were broken into on the same night.', 'https://leetcode.com/problems/house-robber/'),
('dsa-035', '1D Dynamic Programming', 'Longest Palindromic Substring', '', 'Medium', 'Given a string s, return the longest palindromic substring in s.', 'https://leetcode.com/problems/longest-palindromic-substring/'),
('dsa-036', '2D Dynamic Programming', 'Unique Paths', '', 'Medium', 'There is a robot on an m x n grid. The robot is initially located at the top-left corner (i.e., grid[0][0]). The robot tries to move to the bottom-right corner (i.e., grid[m - 1][n - 1]). The robot can only move either down or right at any point in time.', 'https://leetcode.com/problems/unique-paths/'),
('dsa-037', '2D Dynamic Programming', 'Longest Common Subsequence', '', 'Medium', 'Given two strings text1 and text2, return the length of their longest common subsequence. If there is no common subsequence, return 0.', 'https://leetcode.com/problems/longest-common-subsequence/'),
('dsa-038', '2D Dynamic Programming', 'Best Time to Buy and Sell Stock with Cooldown', '', 'Medium', 'You are given an array prices where prices[i] is the price of a given stock on the ith day. Find the maximum profit you can achieve. You may complete as many transactions as you like with the following restriction: After you sell your stock, you cannot buy stock on the next day (i.e., cooldown one day).', 'https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/'),
('dsa-039', 'Bit Manipulation', 'Single Number', '', 'Easy', 'Given a non-empty array of integers nums, every element appears twice except for one. Find that single one. You must implement a solution with a linear runtime complexity and use only constant extra space.', 'https://leetcode.com/problems/single-number/'),
('dsa-040', 'Bit Manipulation', 'Number of 1 Bits', '', 'Easy', 'Write a function that takes the binary representation of an unsigned integer and returns the number of ''1'' bits it has (also known as the Hamming weight).', 'https://leetcode.com/problems/number-of-1-bits/')
ON CONFLICT (id) DO NOTHING;